function [fitresult, gof] = Exponential_fit(power_dbm_output, Voltage_mV)
%CREATEFIT(POWER_DBM_OUTPUT,VOLTAGE_MV)
%  Create a fit.
%
%  Data for 'Power bolometer Vs Voltage Diode' fit:
%      X Input: power_dbm_output
%      Y Output: Voltage_mV
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 17-Apr-2023 15:24:36


%% Fit: 'Power bolometer Vs Voltage Diode'.
[xData, yData] = prepareCurveData( power_dbm_output, Voltage_mV );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [25.4158782209193 0.18733227820288];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'Power bolometer Vs Voltage Diode' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, xData, yData );
legend( h, 'Voltage_mV vs. power_dbm_output', 'Power bolometer Vs Voltage Diode', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'power_dbm_output', 'Interpreter', 'none' );
ylabel( 'Voltage_mV', 'Interpreter', 'none' );
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult, xData, yData, 'residuals' );
legend( h, 'Power bolometer Vs Voltage Diode - residuals', 'Zero Line', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'power_dbm_output', 'Interpreter', 'none' );
ylabel( 'Voltage_mV', 'Interpreter', 'none' );
grid on


