function [fitresult, gof] = Sine(Length, Capacity_voltage_mv)
%CREATEFIT(LENGTH,CAPACITY_VOLTAGE_MV)
%  Create a fit.
%
%  Data for 'sine fit' fit:
%      X Input: Length
%      Y Output: Capacity_voltage_mv
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 17-Apr-2023 15:50:44


%% Fit: 'sine fit'.
[xData, yData] = prepareCurveData( Length, Capacity_voltage_mv );

% Set up fittype and options.
ft = fittype( 'sin1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf];
opts.StartPoint = [4.53620619514153 0.314159265358979 0.464849690648496];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'sine fit' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, xData, yData );
legend( h, 'Capacity_voltage_mv vs. Length', 'sine fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Length', 'Interpreter', 'none' );
ylabel( 'Capacity_voltage_mv', 'Interpreter', 'none' );
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult, xData, yData, 'residuals' );
legend( h, 'sine fit - residuals', 'Zero Line', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Length', 'Interpreter', 'none' );
ylabel( 'Capacity_voltage_mv', 'Interpreter', 'none' );
grid on


