function [fitresult, gof] = Fitareaof2nd(power_dbm_output, Voltage_mV)
%CREATEFIT(POWER_DBM_OUTPUT,VOLTAGE_MV)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: power_dbm_output
%      Y Output: Voltage_mV
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 17-Apr-2023 21:11:46


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( power_dbm_output, Voltage_mV );

% Set up fittype and options.
ft = fittype( '(b*x-a)^(2)+3', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-5 0.5];
opts.StartPoint = [10 1];
opts.Upper = [30 4];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'Voltage_mV vs. power_dbm_output', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'power_dbm_output', 'Interpreter', 'none' );
ylabel( 'Voltage_mV', 'Interpreter', 'none' );
grid on


