function [fitresult, gof] = Sine2sum(Length, short_voltage_mv_8Ghz)
%CREATEFIT(LENGTH,SHORT_VOLTAGE_MV_8GHZ)
%  Create a fit.
%
%  Data for 'sine fit' fit:
%      X Input: Length
%      Y Output: short_voltage_mv_8Ghz
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 17-Apr-2023 15:57:08


%% Fit: 'sine fit'.
[xData, yData] = prepareCurveData( Length, short_voltage_mv_8Ghz );

% Set up fittype and options.
ft = fittype( 'sin2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf -Inf 0 -Inf];
opts.StartPoint = [13.5894507183598 0.314159265358979 0.464292924014743 11.7894753981932 1.88495559215388 1.43280672818991];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'sine fit' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, xData, yData );
legend( h, 'short_voltage_mv_8Ghz vs. Length', 'sine fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Length', 'Interpreter', 'none' );
ylabel( 'short_voltage_mv_8Ghz', 'Interpreter', 'none' );
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult, xData, yData, 'residuals' );
legend( h, 'sine fit - residuals', 'Zero Line', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Length', 'Interpreter', 'none' );
ylabel( 'short_voltage_mv_8Ghz', 'Interpreter', 'none' );
grid on


